// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.4
// source: goods/goods.proto

package goods

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品详情信息
type GoodsDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	BrandName     string                 `protobuf:"bytes,5,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	MarketPrice   string                 `protobuf:"bytes,6,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"` // 市场价格（字符串格式，如"99.99"）
	Price         string                 `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`                                // 销售价格（字符串格式，如"89.99"）
	Brief         string                 `protobuf:"bytes,8,opt,name=brief,proto3" json:"brief,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsDetailResponse) Reset() {
	*x = GoodsDetailResponse{}
	mi := &file_goods_goods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetailResponse) ProtoMessage() {}

func (x *GoodsDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetailResponse.ProtoReflect.Descriptor instead.
func (*GoodsDetailResponse) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsDetailResponse) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsDetailResponse) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsDetailResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GoodsDetailResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GoodsDetailResponse) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *GoodsDetailResponse) GetMarketPrice() string {
	if x != nil {
		return x.MarketPrice
	}
	return ""
}

func (x *GoodsDetailResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GoodsDetailResponse) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *GoodsDetailResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 商品简要信息（用于列表）
type GoodsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	MarketPrice   string                 `protobuf:"bytes,5,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Brief         string                 `protobuf:"bytes,7,opt,name=brief,proto3" json:"brief,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfo) Reset() {
	*x = GoodsInfo{}
	mi := &file_goods_goods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfo) ProtoMessage() {}

func (x *GoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfo.ProtoReflect.Descriptor instead.
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsInfo) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsInfo) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GoodsInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GoodsInfo) GetMarketPrice() string {
	if x != nil {
		return x.MarketPrice
	}
	return ""
}

func (x *GoodsInfo) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GoodsInfo) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

// 获取直播间商品请求
type GetGoodsByRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        int64                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodsByRoomRequest) Reset() {
	*x = GetGoodsByRoomRequest{}
	mi := &file_goods_goods_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsByRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsByRoomRequest) ProtoMessage() {}

func (x *GetGoodsByRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsByRoomRequest.ProtoReflect.Descriptor instead.
func (*GetGoodsByRoomRequest) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{2}
}

func (x *GetGoodsByRoomRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetGoodsByRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 获取直播间商品响应
type GetGoodsByRoomResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentGoodsId int64                  `protobuf:"varint,1,opt,name=current_goods_id,json=currentGoodsId,proto3" json:"current_goods_id,omitempty"`
	Data           []*GoodsInfo           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetGoodsByRoomResponse) Reset() {
	*x = GetGoodsByRoomResponse{}
	mi := &file_goods_goods_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsByRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsByRoomResponse) ProtoMessage() {}

func (x *GetGoodsByRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsByRoomResponse.ProtoReflect.Descriptor instead.
func (*GetGoodsByRoomResponse) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{3}
}

func (x *GetGoodsByRoomResponse) GetCurrentGoodsId() int64 {
	if x != nil {
		return x.CurrentGoodsId
	}
	return 0
}

func (x *GetGoodsByRoomResponse) GetData() []*GoodsInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取商品详情请求
type GetGoodsDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodsDetailRequest) Reset() {
	*x = GetGoodsDetailRequest{}
	mi := &file_goods_goods_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsDetailRequest) ProtoMessage() {}

func (x *GetGoodsDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsDetailRequest.ProtoReflect.Descriptor instead.
func (*GetGoodsDetailRequest) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{4}
}

func (x *GetGoodsDetailRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GetGoodsDetailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取商品详情响应
type GetGoodsDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goods         *GoodsDetailResponse   `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodsDetailResponse) Reset() {
	*x = GetGoodsDetailResponse{}
	mi := &file_goods_goods_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsDetailResponse) ProtoMessage() {}

func (x *GetGoodsDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsDetailResponse.ProtoReflect.Descriptor instead.
func (*GetGoodsDetailResponse) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{5}
}

func (x *GetGoodsDetailResponse) GetGoods() *GoodsDetailResponse {
	if x != nil {
		return x.Goods
	}
	return nil
}

// 更新商品详情请求
type UpdateGoodsDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"` // 价格（分为单位）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoodsDetailRequest) Reset() {
	*x = UpdateGoodsDetailRequest{}
	mi := &file_goods_goods_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoodsDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsDetailRequest) ProtoMessage() {}

func (x *UpdateGoodsDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsDetailRequest.ProtoReflect.Descriptor instead.
func (*UpdateGoodsDetailRequest) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGoodsDetailRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *UpdateGoodsDetailRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// 更新商品详情响应
type UpdateGoodsDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoodsDetailResponse) Reset() {
	*x = UpdateGoodsDetailResponse{}
	mi := &file_goods_goods_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoodsDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsDetailResponse) ProtoMessage() {}

func (x *UpdateGoodsDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsDetailResponse.ProtoReflect.Descriptor instead.
func (*UpdateGoodsDetailResponse) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGoodsDetailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateGoodsDetailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_goods_goods_proto protoreflect.FileDescriptor

const file_goods_goods_proto_rawDesc = "" +
	"\n" +
	"\x11goods/goods.proto\x12\x05goods\"\x81\x02\n" +
	"\x13GoodsDetailResponse\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x03R\agoodsId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x05 \x01(\tR\tbrandName\x12!\n" +
	"\fmarket_price\x18\x06 \x01(\tR\vmarketPrice\x12\x14\n" +
	"\x05price\x18\a \x01(\tR\x05price\x12\x14\n" +
	"\x05brief\x18\b \x01(\tR\x05brief\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\"\xc4\x01\n" +
	"\tGoodsInfo\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x03R\agoodsId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12!\n" +
	"\fmarket_price\x18\x05 \x01(\tR\vmarketPrice\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x14\n" +
	"\x05brief\x18\a \x01(\tR\x05brief\"I\n" +
	"\x15GetGoodsByRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x03R\x06roomId\"h\n" +
	"\x16GetGoodsByRoomResponse\x12(\n" +
	"\x10current_goods_id\x18\x01 \x01(\x03R\x0ecurrentGoodsId\x12$\n" +
	"\x04data\x18\x02 \x03(\v2\x10.goods.GoodsInfoR\x04data\"K\n" +
	"\x15GetGoodsDetailRequest\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x03R\agoodsId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"J\n" +
	"\x16GetGoodsDetailResponse\x120\n" +
	"\x05goods\x18\x01 \x01(\v2\x1a.goods.GoodsDetailResponseR\x05goods\"K\n" +
	"\x18UpdateGoodsDetailRequest\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x03R\agoodsId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\"O\n" +
	"\x19UpdateGoodsDetailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x84\x02\n" +
	"\fGoodsService\x12M\n" +
	"\x0eGetGoodsByRoom\x12\x1c.goods.GetGoodsByRoomRequest\x1a\x1d.goods.GetGoodsByRoomResponse\x12M\n" +
	"\x0eGetGoodsDetail\x12\x1c.goods.GetGoodsDetailRequest\x1a\x1d.goods.GetGoodsDetailResponse\x12V\n" +
	"\x11UpdateGoodsDetail\x12\x1f.goods.UpdateGoodsDetailRequest\x1a .goods.UpdateGoodsDetailResponseB!Z\x1fmicroservices-goods-proto/goodsb\x06proto3"

var (
	file_goods_goods_proto_rawDescOnce sync.Once
	file_goods_goods_proto_rawDescData []byte
)

func file_goods_goods_proto_rawDescGZIP() []byte {
	file_goods_goods_proto_rawDescOnce.Do(func() {
		file_goods_goods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goods_goods_proto_rawDesc), len(file_goods_goods_proto_rawDesc)))
	})
	return file_goods_goods_proto_rawDescData
}

var file_goods_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_goods_goods_proto_goTypes = []any{
	(*GoodsDetailResponse)(nil),       // 0: goods.GoodsDetailResponse
	(*GoodsInfo)(nil),                 // 1: goods.GoodsInfo
	(*GetGoodsByRoomRequest)(nil),     // 2: goods.GetGoodsByRoomRequest
	(*GetGoodsByRoomResponse)(nil),    // 3: goods.GetGoodsByRoomResponse
	(*GetGoodsDetailRequest)(nil),     // 4: goods.GetGoodsDetailRequest
	(*GetGoodsDetailResponse)(nil),    // 5: goods.GetGoodsDetailResponse
	(*UpdateGoodsDetailRequest)(nil),  // 6: goods.UpdateGoodsDetailRequest
	(*UpdateGoodsDetailResponse)(nil), // 7: goods.UpdateGoodsDetailResponse
}
var file_goods_goods_proto_depIdxs = []int32{
	1, // 0: goods.GetGoodsByRoomResponse.data:type_name -> goods.GoodsInfo
	0, // 1: goods.GetGoodsDetailResponse.goods:type_name -> goods.GoodsDetailResponse
	2, // 2: goods.GoodsService.GetGoodsByRoom:input_type -> goods.GetGoodsByRoomRequest
	4, // 3: goods.GoodsService.GetGoodsDetail:input_type -> goods.GetGoodsDetailRequest
	6, // 4: goods.GoodsService.UpdateGoodsDetail:input_type -> goods.UpdateGoodsDetailRequest
	3, // 5: goods.GoodsService.GetGoodsByRoom:output_type -> goods.GetGoodsByRoomResponse
	5, // 6: goods.GoodsService.GetGoodsDetail:output_type -> goods.GetGoodsDetailResponse
	7, // 7: goods.GoodsService.UpdateGoodsDetail:output_type -> goods.UpdateGoodsDetailResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_goods_goods_proto_init() }
func file_goods_goods_proto_init() {
	if File_goods_goods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goods_goods_proto_rawDesc), len(file_goods_goods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_goods_proto_goTypes,
		DependencyIndexes: file_goods_goods_proto_depIdxs,
		MessageInfos:      file_goods_goods_proto_msgTypes,
	}.Build()
	File_goods_goods_proto = out.File
	file_goods_goods_proto_goTypes = nil
	file_goods_goods_proto_depIdxs = nil
}
