// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	gateway "api-gateway/internal/handler/gateway"
	"api-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/order/create",
				Handler: gateway.CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/order/list",
				Handler: gateway.GetOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/order/detail",
				Handler: gateway.GetOrderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/order/status",
				Handler: gateway.UpdateOrderStatusHandler(serverCtx),
			},
		},
	)
}
