// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	gateway "api-gateway/internal/handler/gateway"
	"api-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/goods/detail",
				Handler: gateway.ProxyGetGoodsDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/goods/room",
				Handler: gateway.ProxyGetGoodsByRoomHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/goods/update",
				Handler: gateway.ProxyUpdateGoodsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
