// Code generated by goctl. DO NOT EDIT.
package types

type CreateOrderRequest struct {
	GoodsId int64  `json:"goods_id"` // 商品ID
	Num     int32  `json:"num"`      // 商品数量
	UserId  int64  `json:"user_id"`  // 用户ID
	Address string `json:"address"`  // 收货地址
	Name    string `json:"name"`     // 收货人姓名
	Phone   string `json:"phone"`    // 收货人电话
}

type CreateOrderResponse struct {
	Success bool   `json:"success"`  // 操作状态
	Message string `json:"message"`  // 响应消息
	OrderId int64  `json:"order_id"` // 订单ID
	Price   string `json:"price"`    // 商品价格
}

type GetOrderListRequest struct {
	UserId   int64 `form:"user_id"`   // 用户ID
	PageNum  int32 `form:"page_num"`  // 当前页码
	PageSize int32 `form:"page_size"` // 每页大小
}

type OrderDetailInfo struct {
	OrderId   int64  `json:"order_id"`   // 订单ID
	GoodsId   int64  `json:"goods_id"`   // 商品ID
	Num       int64  `json:"num"`        // 商品数量
	Title     string `json:"title"`      // 商品标题
	Status    string `json:"status"`     // 详情状态
	Price     int64  `json:"price"`      // 商品价格（分）
	Brief     string `json:"brief"`      // 商品简介
	PayAmount int64  `json:"pay_amount"` // 支付金额（分）
}

type OrderInfo struct {
	OrderId        int64             `json:"order_id"`        // 订单ID
	UserId         int64             `json:"user_id"`         // 用户ID
	Status         string            `json:"status"`          // 订单状态
	PayChannel     string            `json:"pay_channel"`     // 支付渠道
	PayAmount      int64             `json:"pay_amount"`      // 支付金额（分）
	ReceiveAddress string            `json:"receive_address"` // 收货地址
	ReceiveName    string            `json:"receive_name"`    // 收货人姓名
	ReceivePhone   string            `json:"receive_phone"`   // 收货人电话
	CreatedAt      int64             `json:"created_at"`      // 创建时间
	OrderDetails   []OrderDetailInfo `json:"order_details"`   // 订单详情列表
}

type GetOrderListResponse struct {
	Total  int32       `json:"total"`  // 总记录数
	Orders []OrderInfo `json:"orders"` // 订单信息列表
}

type GetOrderDetailRequest struct {
	OrderId int64 `form:"order_id"` // 订单ID
	UserId  int64 `form:"user_id"`  // 用户ID
}

type GetOrderDetailResponse struct {
	Order OrderInfo `json:"order"` // 订单信息
}

type UpdateOrderStatusRequest struct {
	OrderId int64  `json:"order_id"` // 订单ID
	Status  string `json:"status"`   // 新的订单状态
}

type UpdateOrderStatusResponse struct {
	Success bool   `json:"success"` // 操作状态
	Message string `json:"message"` // 响应消息
}




