// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: stock/stock.proto

package stock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StockService_SetStock_FullMethodName         = "/stock.StockService/SetStock"
	StockService_GetStock_FullMethodName         = "/stock.StockService/GetStock"
	StockService_ReduceStock_FullMethodName      = "/stock.StockService/ReduceStock"
	StockService_RollbackStock_FullMethodName    = "/stock.StockService/RollbackStock"
	StockService_BatchGetStock_FullMethodName    = "/stock.StockService/BatchGetStock"
	StockService_BatchReduceStock_FullMethodName = "/stock.StockService/BatchReduceStock"
)

// StockServiceClient is the client API for StockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockServiceClient interface {
	// 设置库存
	SetStock(ctx context.Context, in *GoodsStockInfo, opts ...grpc.CallOption) (*Response, error)
	// 获取库存
	GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GoodsStockInfo, error)
	// 减少库存
	ReduceStock(ctx context.Context, in *ReduceStockInfo, opts ...grpc.CallOption) (*Response, error)
	// 回滚库存
	RollbackStock(ctx context.Context, in *RollBackStockInfo, opts ...grpc.CallOption) (*Response, error)
	// 批量获取库存
	BatchGetStock(ctx context.Context, in *StockInfoList, opts ...grpc.CallOption) (*StockInfoList, error)
	// 批量减少库存
	BatchReduceStock(ctx context.Context, in *StockInfoList, opts ...grpc.CallOption) (*Response, error)
}

type stockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockServiceClient(cc grpc.ClientConnInterface) StockServiceClient {
	return &stockServiceClient{cc}
}

func (c *stockServiceClient) SetStock(ctx context.Context, in *GoodsStockInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, StockService_SetStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GoodsStockInfo, error) {
	out := new(GoodsStockInfo)
	err := c.cc.Invoke(ctx, StockService_GetStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) ReduceStock(ctx context.Context, in *ReduceStockInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, StockService_ReduceStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) RollbackStock(ctx context.Context, in *RollBackStockInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, StockService_RollbackStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) BatchGetStock(ctx context.Context, in *StockInfoList, opts ...grpc.CallOption) (*StockInfoList, error) {
	out := new(StockInfoList)
	err := c.cc.Invoke(ctx, StockService_BatchGetStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) BatchReduceStock(ctx context.Context, in *StockInfoList, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, StockService_BatchReduceStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockServiceServer is the server API for StockService service.
// All implementations must embed UnimplementedStockServiceServer
// for forward compatibility
type StockServiceServer interface {
	// 设置库存
	SetStock(context.Context, *GoodsStockInfo) (*Response, error)
	// 获取库存
	GetStock(context.Context, *GetStockRequest) (*GoodsStockInfo, error)
	// 减少库存
	ReduceStock(context.Context, *ReduceStockInfo) (*Response, error)
	// 回滚库存
	RollbackStock(context.Context, *RollBackStockInfo) (*Response, error)
	// 批量获取库存
	BatchGetStock(context.Context, *StockInfoList) (*StockInfoList, error)
	// 批量减少库存
	BatchReduceStock(context.Context, *StockInfoList) (*Response, error)
	mustEmbedUnimplementedStockServiceServer()
}

// UnimplementedStockServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStockServiceServer struct {
}

func (UnimplementedStockServiceServer) SetStock(context.Context, *GoodsStockInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStock not implemented")
}
func (UnimplementedStockServiceServer) GetStock(context.Context, *GetStockRequest) (*GoodsStockInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedStockServiceServer) ReduceStock(context.Context, *ReduceStockInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReduceStock not implemented")
}
func (UnimplementedStockServiceServer) RollbackStock(context.Context, *RollBackStockInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackStock not implemented")
}
func (UnimplementedStockServiceServer) BatchGetStock(context.Context, *StockInfoList) (*StockInfoList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetStock not implemented")
}
func (UnimplementedStockServiceServer) BatchReduceStock(context.Context, *StockInfoList) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchReduceStock not implemented")
}
func (UnimplementedStockServiceServer) mustEmbedUnimplementedStockServiceServer() {}

// UnsafeStockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockServiceServer will
// result in compilation errors.
type UnsafeStockServiceServer interface {
	mustEmbedUnimplementedStockServiceServer()
}

func RegisterStockServiceServer(s grpc.ServiceRegistrar, srv StockServiceServer) {
	s.RegisterService(&StockService_ServiceDesc, srv)
}

func _StockService_SetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsStockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).SetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_SetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).SetStock(ctx, req.(*GoodsStockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_GetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetStock(ctx, req.(*GetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_ReduceStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReduceStockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).ReduceStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_ReduceStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).ReduceStock(ctx, req.(*ReduceStockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_RollbackStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollBackStockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).RollbackStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_RollbackStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).RollbackStock(ctx, req.(*RollBackStockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_BatchGetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfoList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).BatchGetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_BatchGetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).BatchGetStock(ctx, req.(*StockInfoList))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_BatchReduceStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfoList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).BatchReduceStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_BatchReduceStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).BatchReduceStock(ctx, req.(*StockInfoList))
	}
	return interceptor(ctx, in, info, handler)
}

// StockService_ServiceDesc is the grpc.ServiceDesc for StockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock.StockService",
	HandlerType: (*StockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetStock",
			Handler:    _StockService_SetStock_Handler,
		},
		{
			MethodName: "GetStock",
			Handler:    _StockService_GetStock_Handler,
		},
		{
			MethodName: "ReduceStock",
			Handler:    _StockService_ReduceStock_Handler,
		},
		{
			MethodName: "RollbackStock",
			Handler:    _StockService_RollbackStock_Handler,
		},
		{
			MethodName: "BatchGetStock",
			Handler:    _StockService_BatchGetStock_Handler,
		},
		{
			MethodName: "BatchReduceStock",
			Handler:    _StockService_BatchReduceStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock/stock.proto",
}
