// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.4
// source: proto/stock.proto

package stock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用响应消息
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 操作是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 操作结果描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_stock_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取库存请求
type GetStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"` // 商品ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockReq) Reset() {
	*x = GetStockReq{}
	mi := &file_proto_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockReq) ProtoMessage() {}

func (x *GetStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockReq.ProtoReflect.Descriptor instead.
func (*GetStockReq) Descriptor() ([]byte, []int) {
	return file_proto_stock_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

// 商品库存信息
type GoodsStockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"` // 商品ID
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`                    // 库存数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsStockInfo) Reset() {
	*x = GoodsStockInfo{}
	mi := &file_proto_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsStockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsStockInfo) ProtoMessage() {}

func (x *GoodsStockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsStockInfo.ProtoReflect.Descriptor instead.
func (*GoodsStockInfo) Descriptor() ([]byte, []int) {
	return file_proto_stock_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsStockInfo) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsStockInfo) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

// 扣减库存信息
type ReduceStockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"` // 商品ID
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`                        // 下单商品数量（扣减库存数量）
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单ID（可选字段，仅在扣减库存时使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceStockInfo) Reset() {
	*x = ReduceStockInfo{}
	mi := &file_proto_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceStockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceStockInfo) ProtoMessage() {}

func (x *ReduceStockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceStockInfo.ProtoReflect.Descriptor instead.
func (*ReduceStockInfo) Descriptor() ([]byte, []int) {
	return file_proto_stock_proto_rawDescGZIP(), []int{3}
}

func (x *ReduceStockInfo) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *ReduceStockInfo) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ReduceStockInfo) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// 库存信息列表
type StockInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*GoodsStockInfo      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // 库存信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfoList) Reset() {
	*x = StockInfoList{}
	mi := &file_proto_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfoList) ProtoMessage() {}

func (x *StockInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfoList.ProtoReflect.Descriptor instead.
func (*StockInfoList) Descriptor() ([]byte, []int) {
	return file_proto_stock_proto_rawDescGZIP(), []int{4}
}

func (x *StockInfoList) GetData() []*GoodsStockInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_stock_proto protoreflect.FileDescriptor

const file_proto_stock_proto_rawDesc = "" +
	"\n" +
	"\x11proto/stock.proto\x12\x05stock\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\vGetStockReq\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x03R\agoodsId\"A\n" +
	"\x0eGoodsStockInfo\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x03R\agoodsId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"Y\n" +
	"\x0fReduceStockInfo\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x03R\agoodsId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\":\n" +
	"\rStockInfoList\x12)\n" +
	"\x04data\x18\x01 \x03(\v2\x15.stock.GoodsStockInfoR\x04data2\xdc\x02\n" +
	"\x05Stock\x122\n" +
	"\bSetStock\x12\x15.stock.GoodsStockInfo\x1a\x0f.stock.Response\x125\n" +
	"\bGetStock\x12\x12.stock.GetStockReq\x1a\x15.stock.GoodsStockInfo\x126\n" +
	"\vReduceStock\x12\x16.stock.ReduceStockInfo\x1a\x0f.stock.Response\x128\n" +
	"\rRollbackStock\x12\x16.stock.ReduceStockInfo\x1a\x0f.stock.Response\x12;\n" +
	"\rBatchGetStock\x12\x14.stock.StockInfoList\x1a\x14.stock.StockInfoList\x129\n" +
	"\x10BatchReduceStock\x12\x14.stock.StockInfoList\x1a\x0f.stock.ResponseB\x1fZ\x1dorder-rpc-service/proto/stockb\x06proto3"

var (
	file_proto_stock_proto_rawDescOnce sync.Once
	file_proto_stock_proto_rawDescData []byte
)

func file_proto_stock_proto_rawDescGZIP() []byte {
	file_proto_stock_proto_rawDescOnce.Do(func() {
		file_proto_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stock_proto_rawDesc), len(file_proto_stock_proto_rawDesc)))
	})
	return file_proto_stock_proto_rawDescData
}

var file_proto_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_stock_proto_goTypes = []any{
	(*Response)(nil),        // 0: stock.Response
	(*GetStockReq)(nil),     // 1: stock.GetStockReq
	(*GoodsStockInfo)(nil),  // 2: stock.GoodsStockInfo
	(*ReduceStockInfo)(nil), // 3: stock.ReduceStockInfo
	(*StockInfoList)(nil),   // 4: stock.StockInfoList
}
var file_proto_stock_proto_depIdxs = []int32{
	2, // 0: stock.StockInfoList.data:type_name -> stock.GoodsStockInfo
	2, // 1: stock.Stock.SetStock:input_type -> stock.GoodsStockInfo
	1, // 2: stock.Stock.GetStock:input_type -> stock.GetStockReq
	3, // 3: stock.Stock.ReduceStock:input_type -> stock.ReduceStockInfo
	3, // 4: stock.Stock.RollbackStock:input_type -> stock.ReduceStockInfo
	4, // 5: stock.Stock.BatchGetStock:input_type -> stock.StockInfoList
	4, // 6: stock.Stock.BatchReduceStock:input_type -> stock.StockInfoList
	0, // 7: stock.Stock.SetStock:output_type -> stock.Response
	2, // 8: stock.Stock.GetStock:output_type -> stock.GoodsStockInfo
	0, // 9: stock.Stock.ReduceStock:output_type -> stock.Response
	0, // 10: stock.Stock.RollbackStock:output_type -> stock.Response
	4, // 11: stock.Stock.BatchGetStock:output_type -> stock.StockInfoList
	0, // 12: stock.Stock.BatchReduceStock:output_type -> stock.Response
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stock_proto_init() }
func file_proto_stock_proto_init() {
	if File_proto_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stock_proto_rawDesc), len(file_proto_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stock_proto_goTypes,
		DependencyIndexes: file_proto_stock_proto_depIdxs,
		MessageInfos:      file_proto_stock_proto_msgTypes,
	}.Build()
	File_proto_stock_proto = out.File
	file_proto_stock_proto_goTypes = nil
	file_proto_stock_proto_depIdxs = nil
}
