// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type GetGoodsByRoomReq struct {
	UserId int64 `form:"user_id"`
	RoomId int64 `form:"room_id" validate:"required,min=1"`
}

type GetGoodsDetailReq struct {
	GoodsId int64 `form:"goods_id" validate:"required,min=1"`
	UserId  int64 `form:"user_id"`
}

type GoodsDetail struct {
	GoodsId     int64  `json:"goods_id"`
	CategoryId  int64  `json:"category_id"`
	Status      int32  `json:"status"`
	Title       string `json:"title"`
	Code        string `json:"code"`
	BrandName   string `json:"brand_name"`
	MarketPrice string `json:"market_price"`
	Price       string `json:"price"`
	Brief       string `json:"brief"`
}

type GoodsInfo struct {
	GoodsId     int64  `json:"goods_id"`
	CategoryId  int64  `json:"category_id"`
	Status      int32  `json:"status"`
	Title       string `json:"title"`
	MarketPrice string `json:"market_price"`
	Price       string `json:"price"`
	Brief       string `json:"brief"`
}

type GoodsListResp struct {
	CurrentGoodsId int64        `json:"current_goods_id"`
	Data           []*GoodsInfo `json:"data"`
}

type Response struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type UpdateGoodsDetailReq struct {
	GoodsId int64 `json:"goods_id" validate:"required,min=1"`
	Price   int64 `json:"price" validate:"required,min=1"`
}
