// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.4
// source: proto/goods.proto

package goods

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取直播间商品列表请求
type GetGoodsByRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` // 用户 ID
	RoomId        int64                  `protobuf:"varint,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"` // 直播间 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodsByRoomReq) Reset() {
	*x = GetGoodsByRoomReq{}
	mi := &file_proto_goods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsByRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsByRoomReq) ProtoMessage() {}

func (x *GetGoodsByRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsByRoomReq.ProtoReflect.Descriptor instead.
func (*GetGoodsByRoomReq) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{0}
}

func (x *GetGoodsByRoomReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetGoodsByRoomReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 商品列表响应
type GoodsListResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentGoodsId int64                  `protobuf:"varint,1,opt,name=CurrentGoodsId,proto3" json:"CurrentGoodsId,omitempty"` // 当前商品的 ID
	Data           []*GoodsInfo           `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`                      // 商品列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GoodsListResp) Reset() {
	*x = GoodsListResp{}
	mi := &file_proto_goods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsListResp) ProtoMessage() {}

func (x *GoodsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsListResp.ProtoReflect.Descriptor instead.
func (*GoodsListResp) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsListResp) GetCurrentGoodsId() int64 {
	if x != nil {
		return x.CurrentGoodsId
	}
	return 0
}

func (x *GoodsListResp) GetData() []*GoodsInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 商品信息
type GoodsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`        // 商品 ID
	CategoryId    int64                  `protobuf:"varint,2,opt,name=CategoryId,proto3" json:"CategoryId,omitempty"`  // 分类 ID
	Status        int32                  `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`          // 商品状态
	Title         string                 `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`             // 商品标题
	MarketPrice   string                 `protobuf:"bytes,5,opt,name=MarketPrice,proto3" json:"MarketPrice,omitempty"` // 市场价格
	Price         string                 `protobuf:"bytes,6,opt,name=Price,proto3" json:"Price,omitempty"`             // 销售价格
	Brief         string                 `protobuf:"bytes,7,opt,name=Brief,proto3" json:"Brief,omitempty"`             // 商品简介
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfo) Reset() {
	*x = GoodsInfo{}
	mi := &file_proto_goods_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfo) ProtoMessage() {}

func (x *GoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfo.ProtoReflect.Descriptor instead.
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsInfo) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsInfo) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GoodsInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GoodsInfo) GetMarketPrice() string {
	if x != nil {
		return x.MarketPrice
	}
	return ""
}

func (x *GoodsInfo) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GoodsInfo) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

// 获取商品详情请求
type GetGoodsDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"` // 商品 ID
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`   // 用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodsDetailReq) Reset() {
	*x = GetGoodsDetailReq{}
	mi := &file_proto_goods_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsDetailReq) ProtoMessage() {}

func (x *GetGoodsDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsDetailReq.ProtoReflect.Descriptor instead.
func (*GetGoodsDetailReq) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{3}
}

func (x *GetGoodsDetailReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GetGoodsDetailReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 商品详情响应
type GoodsDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`        // 商品 ID
	CategoryId    int64                  `protobuf:"varint,2,opt,name=CategoryId,proto3" json:"CategoryId,omitempty"`  // 分类 ID
	Status        int32                  `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`          // 商品状态
	Title         string                 `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`             // 商品标题
	Code          string                 `protobuf:"bytes,5,opt,name=Code,proto3" json:"Code,omitempty"`               // 商品编码
	BrandName     string                 `protobuf:"bytes,6,opt,name=BrandName,proto3" json:"BrandName,omitempty"`     // 品牌名称
	MarketPrice   string                 `protobuf:"bytes,7,opt,name=MarketPrice,proto3" json:"MarketPrice,omitempty"` // 市场价格
	Price         string                 `protobuf:"bytes,8,opt,name=Price,proto3" json:"Price,omitempty"`             // 销售价格
	Brief         string                 `protobuf:"bytes,9,opt,name=Brief,proto3" json:"Brief,omitempty"`             // 商品简介
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsDetail) Reset() {
	*x = GoodsDetail{}
	mi := &file_proto_goods_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetail) ProtoMessage() {}

func (x *GoodsDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetail.ProtoReflect.Descriptor instead.
func (*GoodsDetail) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{4}
}

func (x *GoodsDetail) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsDetail) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GoodsDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GoodsDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GoodsDetail) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *GoodsDetail) GetMarketPrice() string {
	if x != nil {
		return x.MarketPrice
	}
	return ""
}

func (x *GoodsDetail) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GoodsDetail) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

var File_proto_goods_proto protoreflect.FileDescriptor

const file_proto_goods_proto_rawDesc = "" +
	"\n" +
	"\x11proto/goods.proto\x12\x05goods\"C\n" +
	"\x11GetGoodsByRoomReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x16\n" +
	"\x06RoomId\x18\x02 \x01(\x03R\x06RoomId\"]\n" +
	"\rGoodsListResp\x12&\n" +
	"\x0eCurrentGoodsId\x18\x01 \x01(\x03R\x0eCurrentGoodsId\x12$\n" +
	"\x04Data\x18\x02 \x03(\v2\x10.goods.GoodsInfoR\x04Data\"\xc1\x01\n" +
	"\tGoodsInfo\x12\x18\n" +
	"\aGoodsId\x18\x01 \x01(\x03R\aGoodsId\x12\x1e\n" +
	"\n" +
	"CategoryId\x18\x02 \x01(\x03R\n" +
	"CategoryId\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\x05R\x06Status\x12\x14\n" +
	"\x05Title\x18\x04 \x01(\tR\x05Title\x12 \n" +
	"\vMarketPrice\x18\x05 \x01(\tR\vMarketPrice\x12\x14\n" +
	"\x05Price\x18\x06 \x01(\tR\x05Price\x12\x14\n" +
	"\x05Brief\x18\a \x01(\tR\x05Brief\"E\n" +
	"\x11GetGoodsDetailReq\x12\x18\n" +
	"\aGoodsId\x18\x01 \x01(\x03R\aGoodsId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\"\xf5\x01\n" +
	"\vGoodsDetail\x12\x18\n" +
	"\aGoodsId\x18\x01 \x01(\x03R\aGoodsId\x12\x1e\n" +
	"\n" +
	"CategoryId\x18\x02 \x01(\x03R\n" +
	"CategoryId\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\x05R\x06Status\x12\x14\n" +
	"\x05Title\x18\x04 \x01(\tR\x05Title\x12\x12\n" +
	"\x04Code\x18\x05 \x01(\tR\x04Code\x12\x1c\n" +
	"\tBrandName\x18\x06 \x01(\tR\tBrandName\x12 \n" +
	"\vMarketPrice\x18\a \x01(\tR\vMarketPrice\x12\x14\n" +
	"\x05Price\x18\b \x01(\tR\x05Price\x12\x14\n" +
	"\x05Brief\x18\t \x01(\tR\x05Brief2\x89\x01\n" +
	"\x05Goods\x12@\n" +
	"\x0eGetGoodsByRoom\x12\x18.goods.GetGoodsByRoomReq\x1a\x14.goods.GoodsListResp\x12>\n" +
	"\x0eGetGoodsDetail\x12\x18.goods.GetGoodsDetailReq\x1a\x12.goods.GoodsDetailB\x1fZ\x1dorder-rpc-service/proto/goodsb\x06proto3"

var (
	file_proto_goods_proto_rawDescOnce sync.Once
	file_proto_goods_proto_rawDescData []byte
)

func file_proto_goods_proto_rawDescGZIP() []byte {
	file_proto_goods_proto_rawDescOnce.Do(func() {
		file_proto_goods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_goods_proto_rawDesc), len(file_proto_goods_proto_rawDesc)))
	})
	return file_proto_goods_proto_rawDescData
}

var file_proto_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_goods_proto_goTypes = []any{
	(*GetGoodsByRoomReq)(nil), // 0: goods.GetGoodsByRoomReq
	(*GoodsListResp)(nil),     // 1: goods.GoodsListResp
	(*GoodsInfo)(nil),         // 2: goods.GoodsInfo
	(*GetGoodsDetailReq)(nil), // 3: goods.GetGoodsDetailReq
	(*GoodsDetail)(nil),       // 4: goods.GoodsDetail
}
var file_proto_goods_proto_depIdxs = []int32{
	2, // 0: goods.GoodsListResp.Data:type_name -> goods.GoodsInfo
	0, // 1: goods.Goods.GetGoodsByRoom:input_type -> goods.GetGoodsByRoomReq
	3, // 2: goods.Goods.GetGoodsDetail:input_type -> goods.GetGoodsDetailReq
	1, // 3: goods.Goods.GetGoodsByRoom:output_type -> goods.GoodsListResp
	4, // 4: goods.Goods.GetGoodsDetail:output_type -> goods.GoodsDetail
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_goods_proto_init() }
func file_proto_goods_proto_init() {
	if File_proto_goods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_goods_proto_rawDesc), len(file_proto_goods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goods_proto_goTypes,
		DependencyIndexes: file_proto_goods_proto_depIdxs,
		MessageInfos:      file_proto_goods_proto_msgTypes,
	}.Build()
	File_proto_goods_proto = out.File
	file_proto_goods_proto_goTypes = nil
	file_proto_goods_proto_depIdxs = nil
}
